service: import-service
frameworkVersion: '3'
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    IMPORT_BUCKET_NAME: aws-boardgames-shop-uploaded
    IMPORT_CATALOG_NAME: uploaded
    PARSED_CATALOG_NAME: parsed
  iamRoleStatements:
    - Effect: Allow
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::aws-boardgames-shop-uploaded'
    - Effect: Allow
      Action: 's3:*'
      Resource:
        - 'arn:aws:s3:::aws-boardgames-shop-uploaded/*'
    - Effect: Allow
      Action: 'sqs:SendMessage'
      Resource:
        - '*'

functions:
  importProductsFile:
    handler: src/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          cors: true
          authorizer: arn:aws:lambda:us-east-1:154716314884:function:authorization-service-dev-basicAuthorizer
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/importFileParser.handler
    events:
      - s3:
          bucket: aws-boardgames-shop-uploaded
          event: s3:ObjectCreated:*
          existing: true
    environment:
      CATALOG_ITEMS_QUEUE_URL:
        Fn::ImportValue: CatalogItemsQueueUrl